FROM php:7.2-apache
WORKDIR /var/www/html/cloudcsv_api

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git \
    -y libpq-dev

# PDO driver
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo pdo_pgsql

#Install Composer
RUN curl https://getcomposer.org/download/1.10.26/composer.phar --output composer.phar
RUN chmod a+x composer.phar
RUN mv composer.phar /usr/local/bin/composer

RUN a2enmod rewrite

EXPOSE 80

WORKDIR /var/www/html/cloudcsv_api