version: '3'
services:
  cloudcsv-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    volumes:
      - ./etc/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - traefik-network

  cloudcsv-api:
    image: php:7.2-apache
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www/html/cloudcsv_api
    depends_on:
      - cloudcsv-db
    ports:
      - ${API_EXPOSED_PORT}:80
    networks:
      - traefik-network

networks:
  traefik-network:
    external:
      name: traefik_proxynet
