DROP TABLE cloudcsv.users CASCADE;
DROP TABLE cloudcsv.table_storage CASCADE;
DROP TABLE cloudcsv.tables_columns CASCADE;
DROP TABLE cloudcsv.example_dynamic_table CASCADE;
DROP TABLE cloudcsv.notifications_emails CASCADE;
DROP TABLE cloudcsv.delete_log CASCADE;
DROP TABLE cloudcsv.users_sessions CASCADE;
DROP TABLE cloudcsv.example_dynamic_table_delete_records CASCADE;
DROP TABLE cloudcsv.recovered_accounts CASCADE;